/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package escalerasyserpientes.principal;

import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JTextField;

import escalerasyserpientes.codigo.crearTabla;
import escalerasyserpientes.principal.Tabla;
import javax.swing.JButton;

/**
 *
 * @author blue
 */
public class Partida extends javax.swing.JFrame {

    /**
     * Creates new form Partida
     */
    public Partida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TableroPrincipal = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        labeldad = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableroPrincipal.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout TableroPrincipalLayout = new javax.swing.GroupLayout(TableroPrincipal);
        TableroPrincipal.setLayout(TableroPrincipalLayout);
        TableroPrincipalLayout.setHorizontalGroup(
            TableroPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        TableroPrincipalLayout.setVerticalGroup(
            TableroPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        getContentPane().add(TableroPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 460, 440));

        jButton1.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        jButton1.setText("Rodar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 33, 70, 40));

        labeldad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escalerasyserpientes/DadosI/dado1.jpg"))); // NOI18N
        getContentPane().add(labeldad, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 180, 180));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Posicion", "Nombre"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 200, 200));

        jButton2.setFont(new java.awt.Font("Ubuntu", 3, 14)); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 33, 70, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escalerasyserpientes/Imagenes/background2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          Inicio inicio = new Inicio();
              inicio.setVisible(true);
                 this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TableroPrincipal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labeldad;
    // End of variables declaration//GEN-END:variables



    public JPanel getTableroPrincipal() {
        return TableroPrincipal;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public JLabel getLabeldad() {
        return labeldad;
    }
    

   
   
    
    
}
