/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package escalerasyserpientes.principal;

import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JTextField;

import escalerasyserpientes.codigo.crearTabla;
import escalerasyserpientes.principal.Tabla;
import javax.swing.JButton;

/**
 *
 * @author blue
 */
public class Partida extends javax.swing.JFrame {

    /**
     * Creates new form Partida
     */
    public Partida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TableroPrincipal = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        labeldad = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableroPrincipal.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout TableroPrincipalLayout = new javax.swing.GroupLayout(TableroPrincipal);
        TableroPrincipal.setLayout(TableroPrincipalLayout);
        TableroPrincipalLayout.setHorizontalGroup(
            TableroPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        TableroPrincipalLayout.setVerticalGroup(
            TableroPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        getContentPane().add(TableroPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 460, 440));

        jButton1.setText("Iniciar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));

        labeldad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escalerasyserpientes/DadosI/dado1.png"))); // NOI18N
        getContentPane().add(labeldad, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/escalerasyserpientes/Imagenes/background2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 760, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TableroPrincipal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labeldad;
    // End of variables declaration//GEN-END:variables



    public JPanel getTableroPrincipal() {
        return TableroPrincipal;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public JLabel getLabeldad() {
        return labeldad;
    }
    

   
   
    
    
}
